### ISSUE TITLE
无线问题请教。

### ISSUE THREAD

**Issue by i0Ek3** [1zilc/K610d-i5-d3-10.14.5-efi-clover#1]
这里有两个问题想要请教一下：

1. 这里说的无线无解是因为10.14.5的问题吗，还是其它问题呢？我在10.14.3下还是OK的！

2. 另外，你通过无线网卡解决了无线问题，速率如何，有没有测试过有线的速率？无线网卡有具体型号要求吗？

感谢！

**Comment by 1zilc** [comment]
1、无解是因为intel的无线网卡是不可能驱动的和mac的版本无关、如果你是某些博通网卡那么可以免驱,因为白果子的网卡是博通的
2、有线无线我都在用,我那款usb无线网卡速率我觉得还行,usb无线网卡需要单独安装驱动

**Comment by i0Ek3** [comment]
我电脑的型号是炫龙A40，和你机器的配置几乎一模一样，除了我是i7-4710MQ的CPU外。无线网卡也没有更换过，还是原本的AR9485，在10.14.3下正常。所以，理论上，10.14.5应该没有问题。或许你可以参考下这个帖子:http://bbs.pcbeta.com/viewthread-1795746-1-1.html. 另外，你的EFI可以说是很完美了，很厉害，值得研究学习！

**Comment by 1zilc** [comment]
嗯,这个驱动我知道,据说速率不行,但是我没有试过,可以尝试一下

**Comment by i0Ek3** [comment]
ok, 期待你的好消息！我先关了哈～
