### ISSUE TITLE
HDMI无法输出，没有两个小电视

### ISSUE THREAD

**Issue by ajsonx** [1zilc/K610d-i5-d3-10.14.5-efi-clover#10]
# 大佬你好，用了你的包之后发现HDMI无法输出，显存正常2048MB
## 配置
* 机型：i5-D3战神
* 更换了CPU：i7-4700MQ
* 显卡：HD Graphics 4600
* 系统：10.13.6
#### 步骤 1 根据教程修改kext
* 找出kext中的`0600260A` 替换为 `0700260D`  ，重建缓存 
（备注：该处的`0600260A`可搜索到3处，默认指的是最后一处在651216行左右。`0700260D`只有一处，在653000行左右）
* 注入`id`为 `0x0D260007`
#### 调试结果 1
* 显存7MB，花屏，但能连接HDMI，并有两个小电视
* 此时输入`ioreg -l | grep ig-platform-id` 输出为 `"AAPL,ig-platform-id" = <0600260a>`
* `DSDT` 中未发现`ig-platform-id` 字段

#### 步骤2 怀疑显存设置问题
* 651216行的`0600260A` 依然替换为 `0700260D`
* 修改651216行的`0700260D`后的显存定义字段 `00000060` 改为  `00000080`
* 此时注入不注入  `ig-platform-id` 结果一样
#### 调试结果2 多次修改无效
* 显存5mb或者显存3mb

#### 步骤3
* 找出kext中的`0700260D` （653000行处）后的定义字段，替换为`0600260A`后的定义字段  ，重建缓存
此时651216行的`0600260A` 依然替换为 `0700260D` 
* 此时注入不注入  `ig-platform-id` 结果一样
#### 调试结果3 多次测试参数修改无效
* 显存5mb或者显存3mb

## 希望大佬帮忙解决，并且让我疑惑的有几点
* 注入id不成功，始终显示`0600260a`
* 输入命令`kextstat | grep -y AppleIntel` 得到的结果跟预期不符合。始终显示加载HD5000Graphics，但我kext/other里并没有这个文件，目前用的EFI也是大佬你的。
````
-> % kextstat | grep -y AppleIntel
   95    0 0xffffff7f8132e000 0x14f000   0x14f000   com.apple.driver.AppleIntelFramebufferAzul (10.3.6) D36524CE-0E98-3762-8459-610792D46B3B <94 93 50 17 12 11 7 6 5 4 3 1>
   97    0 0xffffff7f82b26000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) 7DFBC6BB-39A0-3639-9683-99472E9AAC69 <96 4 3>
  117    0 0xffffff7f81e28000 0x7b000    0x7b000    com.apple.driver.AppleIntelHD5000Graphics (10.3.6) 2B641DEA-FF69-3979-9F05-F492D1ECA8C1 <93 92 50 12 7 6 5 4 3 1>
````
* 修改显存驱动的`0600260A` 为 `0700260D` 可以HDMI输出，有两个小电视，但显存一直调整不过来
* 方便的话给个联系方式，看下我的详细配置，交流一下。

**Comment by cyixlq** [comment]
```
<dict>
  <key>Comment</key>
  <string> 0x0a260006 9MB cursor bytes (vbo), 2 ports only (RehabMan)</string>
  <key>Disabled</key>
  <false/>
  <key>Find</key>
  <data>
  BgAmCgEDAwMAAAACAAAwAQAAYAA=
  </data>
  <key>InfoPlistPatch</key>
  <false/>
  <key>Name</key>
  <string>com.apple.driver.AppleIntelFramebufferAzul</string>
  <key>Replace</key>
  <data>
  BgAmCgEDAgIAAAACAAAwAQAAkAA=
  </data>
</dict>

<dict>
  <key>Comment</key>
  <string>HDMI-audio, port 0105(12), 0x0a260005 0x0a260006, 0x0d220003, 0x0a2e000a, 0x0a26000a</string>
  <key>Disabled</key>
  <false/>
  <key>Find</key>
  <data>
  AQUJAAAEAACHAAAA
  </data>
  <key>InfoPlistPatch</key>
  <false/>
  <key>Name</key>
  <string>com.apple.driver.AppleIntelFramebufferAzul</string>
  <key>Replace</key>
  <data>
  AQUSAAAIAACHAAAA
  </data>
</dict>

<dict>
  <key>Comment</key>
  <string>0x0a260006, disable 0204 port (RehabMan)</string>
  <key>Disabled</key>
  <false/>
  <key>Find</key>
  <data>
  AgQJAAAEAACHAAAA
  </data>
  <key>InfoPlistPatch</key>
  <false/>
  <key>Name</key>
  <string>com.apple.driver.AppleIntelFramebufferAzul</string>
  <key>Replace</key>
  <data>
  /wAAAAEAAABAAAAA
  </data>
</dict>

<dict>
  <key>Comment</key>
  <string>1536MB -&gt; 2048MB for HD4200_4400_4600 Mobile</string>
  <key>Disabled</key>
  <false/>
  <key>Find</key>
  <data>
  AQMDAwAAAAIAADABAABgAAAAAGA=
  </data>
  <key>InfoPlistPatch</key>
  <false/>
  <key>Name</key>
  <string>AppleIntelFramebufferAzul</string>
  <key>Replace</key>
  <data>
  AQMDAwAAAAIAADABAACQAAAAAIA=
  </data>
</dict>
```
感觉这几个kext补丁可以去了，全部换成Device/Properties的方式打这些补丁

**Comment by jhsking** [comment]
![屏幕截图  2019-11-19 下午07 46 15](https://user-images.githubusercontent.com/56294375/69143999-4646ab80-0b05-11ea-8a8b-c9eecb0517b4.jpg)
我直接这么设置就可以用了

**Comment by ajsonx** [comment]
已解决，参考 ： 
[macOS(High Sierra & Mojave support) on Hasse Shinelon A40L-i5/i7](https://github.com/i0Ek3/Hackintosh_4_Hasee_Shinelon_A40L)
[外接显示器的问题我解决了 ，也是基于ym2008修改的](https://github.com/i0Ek3/Hackintosh_4_Hasee_Shinelon_A40L/issues/4)
