### ISSUE TITLE
更新之后翻车

### ISSUE THREAD

**Issue by BABAICAI** [1zilc/K610d-i5-d3-10.14.5-efi-clover#14]
花屏了

**Comment by 1zilc** [comment]
系统什么版本,花屏能具体描述一下吗

**Comment by BABAICAI** [comment]
14.6版本开机之后苹果进度条走一半,就开始花屏,长按电源睡眠,再次唤醒屏幕又正常了,昨晚尝试注入和hip那个插件都无法解决

**Comment by BABAICAI** [comment]
原先使用第一个版本的efi配合13的系统没有这个问题

**Comment by zhengdaoyi** [comment]
我的uefi启动会花屏，感觉是常见问题了，正常

**Comment by BABAICAI** [comment]
有无第三种解决方案解决花屏问题?我看了别的机型使用这个没有问题,但是我这个型号用了就翻车了,一度怀疑我笔记本屏幕不是原装的

**Comment by zhengdaoyi** [comment]
很多时候 都必须开启csm的啊，不然必定花屏，至少这个型号必须要用

**Comment by zhengdaoyi** [comment]
开了开机过程应该不会有问题了

**Comment by BABAICAI** [comment]
感谢,我今晚回去再折腾一下

**Comment by 1zilc** [comment]
关于花屏这个问题,在显卡驱动正常的情况下,检查csm是否开启,edid是否正确注入,再不行,手动开合笔记本盖,以前还有种改clover分辨率的我没试过,你可以尝试

**Comment by BABAICAI** [comment]
谢谢大佬指点,今晚回去再去研究一下

**Comment by as614001** [comment]
CSM  重新注入EDID 应该都没问题。我刚装时候会出现。重新注入了EDID基本没见过了。最好了关了hidpi 再注入。

**Comment by jhsking** [comment]
这个CSM在哪里啊，我怎么找不到啊，boot只有一个兼容模式啊

**Comment by 1zilc** [comment]
k610d i5 d3 是没有这个选项的 , 这样写是为了让其他使用该配置的机型注意这一点

**Comment by jhsking** [comment]
可是我的10.14.6在更新了一个系统补丁后，chrome里部分内容开始花屏，注入了edid后依然如此。不更新这个补丁没有事，与更新到10.15后一样。在10.15里面也是chrome花屏

**Comment by 1zilc** [comment]
你用的哪个版本的EFI?

**Comment by 1zilc** [comment]
看到一个说的是要注入修改以后的edid http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832969&page=1#pid49691111 <http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1832969&page=1#pid49691111> ,5L ,   实在不行,你换id吧…..

**Comment by jhsking** [comment]
我用的就是你的最新的EFI，另外花屏也就是chrome里面有部分页面花屏，比如Infinity界面下。

**Comment by 1zilc** [comment]
properties 打了相关补丁,现在应该修复了

**Comment by jhsking** [comment]
chrome花屏的问题已经解决了，多谢
