### ISSUE TITLE
大佬，你是在哪屏蔽独显的，怎么开启独显，我用你的EFI文件，我装的是10.13.6.显卡940m我装了驱动发现独显被屏蔽了，开启

### ISSUE THREAD

**Issue by xiao-VIP** [1zilc/K610d-i5-d3-10.14.5-efi-clover#17]

**Comment by zhengdaoyi** [comment]
你要先看看自己电脑是不是不经过核显的，如果不是，那独显不能开启的。当然，独显指的是nvida的，amd的独显应该可行，因为是免驱的。

**Comment by xiao-VIP** [comment]
> 你要先看看自己的电脑是不是不经过核显的，如果不是，那独显不能开启的。当然，独显指的是nvida的，amd的独显应该可行，因为是免驱的。

我用你的EFI文件，我装的是10.13.6.940m显卡我装了驱动发现独显被屏蔽了

**Comment by xiao-VIP** [comment]
> 你要先看看自己的电脑是不是不经过核显的，如果不是，那独显不能开启的。当然，独显指的是nvida的，amd的独显应该可行，因为是免驱的。

大佬回复一下咯

**Comment by zhengdaoyi** [comment]
8是我的efi 是@1zilc  。。。。 独显无解

**Comment by xiao-VIP** [comment]
> 8是我的efi是@ 1zilc 。。。。独显无解

10.13.6显卡可以驱动的，你的EIF文件屏蔽了，怎么修改你的EIF文件开启一下独显

**Comment by xiao-VIP** [comment]
> 8是我的efi是@ 1zilc 。。。。独显无解

10.13.6显卡是能驱动的，你的EIF文件怎么修改开启显卡

**Comment by zhengdaoyi** [comment]
8懂 github的规则，原来不是回复我。建议台式机噢。。。。
还有你的型号讲道理 ，不可能驱动独显。因为许多大神的无解

**Comment by xiao-VIP** [comment]
> 原来不是回复我。建议台式机噢。。。可以驱动啊就是用你的EIF文件驱动就被屏蔽了

**Comment by jhsking** [comment]
940M用10.13.6可以驱动，我查了查好像不行吧

**Comment by xiao-VIP** [comment]
> 940M用10.13.6可以驱动，我查了查好像不行吧
你不用这个EIF就行

**Comment by 1zilc** [comment]
940m能驱动?
