### ISSUE TITLE
大佬15.2版本睡眠唤醒后会自动重启，有解决办法吗？

### ISSUE THREAD

**Issue by msmsde** [1zilc/K610d-i5-d3-10.14.5-efi-clover#18]

**Comment by 1zilc** [comment]
应该是hda和appleALC冲突了，我新开了条10.15.2的分支，修复了这个问题，如果可以的话，你帮我测测呗，如果没问题我就合到master分支，谢谢🙏🙏

**Comment by msmsde** [comment]
我已经滚回14.6了，我升级后无线网卡有很多信道都被屏蔽了，没法用。。。
