### ISSUE TITLE
已经更换博通网卡,最新版本应该是AR9485驱动的问题,导致原本的博通也掉了

### ISSUE THREAD

**Issue by vvqc** [1zilc/K610d-i5-d3-10.14.5-efi-clover#2]
已经更换博通网卡,上个版本没事,最新版本应该是AR9485驱动的问题,导致原本的博通也掉了

**Comment by 1zilc** [comment]
复原S/L/E下的IO80211Family.kext,删除IO80211FamilyV2.kext、AirPortAtheros40.kext,删除other下的ATH9KInjector.kext,并删除相关启动参数

**Comment by vvqc** [comment]
> 复原S/L/E下的IO80211Family.kext,删除IO80211FamilyV2.kext、AirPortAtheros40.kext,删除other下的ATH9KInjector.kext

OK,不过还是建议能出一个懒人版,毕竟AR9485我以前也试过,速度太慢了

**Comment by 1zilc** [comment]
如果您方便的话,可否把原版IO80211Family.kext发我一份,邮件dywzzjx@163.com,谢谢,下个版本我把驱动方式换回来,AR 9485 驱动我只提供方法好了,就不添加到clover中了
