### ISSUE TITLE
老哥你好，跪求解答

### ISSUE THREAD

**Issue by lq736232061** [1zilc/K610d-i5-d3-10.14.5-efi-clover#21]
我是一个萌新，看了黑果小兵的文章，尝试了操作一下，但是总是在苹果加载后开始花屏，网上有人说盖盖子就行，但是我试了不是很行，盖盖子好像不花屏了，但是电脑会重启，我也不知道装黑苹果哪方面有问题，跪求大佬解答，谢谢啦

**Comment by 1zilc** [comment]
在安装阶段,电脑会重启多次,是正常现象哦

**Comment by lq736232061** [comment]
> 在安装阶段，电脑会重启多次，是正常现象哦

我自己最后还是解决了，多谢老哥
