### ISSUE TITLE
建议升级AirportBrcmFixup为2.0.2或更高版本

### ISSUE THREAD

**Issue by vvqc** [1zilc/K610d-i5-d3-10.14.5-efi-clover#22]
10.15中删除了博通的网卡驱动,我的是BCM4322,进入之后不能免驱,所以解决办法是找了10.14里面的驱动放在了kext中,但是远景有说更新AirportBrcmFixup就行.因为是我个例,所以不建议再放一个10.14的驱动了,建议更一下AirportBrcmFixup就好.辛苦作者

**Comment by 1zilc** [comment]
你好, 请问你测试过AirportBrcmFixup 2.0.2 以及更高版本吗? 如果没问题, 可以把你的配置 pull 给我,我合并一下就行了,感谢🙏!

**Comment by 1zilc** [comment]
已更新

**Comment by vvqc** [comment]
> 已更新

我试了你更新的版本,WiFi不行,显示是有图标但是打不开,我给你推一个10.14的kext吧
git太慢了,辛苦一下从某云down吧:链接: https://pan.baidu.com/s/1MR_sCRTgyjGYPlzuBVa-5Q 提取码: tqga
