### ISSUE TITLE
关于HDMI输出问题（非k610d）

### ISSUE THREAD

**Issue by plus1998** [1zilc/K610d-i5-d3-10.14.5-efi-clover#23]
十分感谢您分享的EFI，我成功在k480d下顺利安装10.15.2，但是在外接HDMI时遇到了一些问题。以下是我的电脑配置信息*
**-机型：k480d-i5-d1
-CPU：i5-4210M
-显卡：HD Graphics 4600
-系统：10.15.2**

问题具体表现为： 
**1.开机状态下：通过HDMI外接显示器后马上自动重启，重启后只能进到苹果读条界面，无限循环；**
**2. 接着显示器开机，只能进到苹果读条界面，随后进入无限循环**
我希望您能给我提供一些帮助，感激不尽
-------
显示器为1080P；
关于本机中显示显存2048MB；

**Comment by 1zilc** [comment]
你好,感谢反馈, 请提供一下 你正在使用的 EFI版本 (几月几日更新的EFI , 或是 RELEASE版本号)

**Comment by plus1998** [comment]
> 你好,感谢反馈, 请提供一下 你正在使用的 EFI版本 (几月几日更新的EFI , 或是 RELEASE版本号)

你好，我使用的是10.15.2 releases，黑果小兵的镜像，替换了您分享的EFI才安装的。
同时我的有线网卡不能驱动。。我买了某宝WU810N也没办法驱动。
不过毕竟我的不是K610D，如果你有相关经验可以给一些建议。十分感谢

**Comment by 1zilc** [comment]
hdmi 的问题 我也还没有解决, 可能是hackinTool生成的补丁有问题, WU810N 我在 10.14.6 能够稳定使用,如果你需要的话 我可以提供我的驱动文件给你 , 关于有线网卡,目前是支持Realtek RTL8168/8111 系的,你检查一下你的配置

**Comment by plus1998** [comment]
> hdmi 的问题 我也还没有解决, 可能是hackinTool生成的补丁有问题, WU810N 我在 10.14.6 能够稳定使用,如果你需要的话 我可以提供我的驱动文件给你 , 关于有线网卡,目前是支持Realtek RTL8168/8111 系的,你检查一下你的配置

好的，了解，谢谢。我用你10.15.2 的EFI可以顺利安装10.15.2 ，用10.14.6却无法安装10.14.6。卡在IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0 now 0 sm 0x0k。用10.15.2的EFI引导的安装后10.14.6卡在busy timeout "AppleACPICPU"..

**Comment by 1zilc** [comment]
用最新的EFI安装10.15.2吧,release版本的存在花屏问题

> 在 2020年3月4日，14:15，plusl894860970 <notifications@github.com> 写道：
> 
> 安装后10.

**Comment by plusl894860970** [comment]
> 用最新的EFI安装10.15.2吧,release版本的存在花屏问题
> […](#)
> 在 2020年3月4日，14:15，plusl894860970 ***@***.***> 写道： 安装后10.

我下了最新EFI安装10.14.6之后开机，出现IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0 now 0 sm 0x0。。没法启动。

**Comment by plus1998** [comment]
我弄错了，你的EFI十分好用，我也装了10.14.6，非常感谢你的分享。不过可惜10.15不能装COMFAST的驱动。问题还是一样，有线网还是不能用，不过已经可以使用了，再次感谢你！！
