### ISSUE TITLE
请问，15..2安装成功 了，直接替换了 EFI 文件 系统直接进不去是怎么回事，卡苹果logo ，进度条也不显示

### ISSUE THREAD

**Issue by DANGXingJie** [1zilc/K610d-i5-d3-10.14.5-efi-clover#24]

**Comment by 1zilc** [comment]
你好,感谢反馈, 请提供一下 你正在使用的 EFI版本 (几月几日更新的EFI , 或是 RELEASE版本号) 方便我排查问题

**Comment by DANGXingJie** [comment]
用的是您 八天之前更新的EFI,理论支持15.3 ， 我现在安装好的是15.2 ，用回之前14.6 的EFI 可以进去，但是屏幕调60Hz会闪屏（之前14.6也是这个问题），所以想更新15.2，更新EFI 看能不解决，结果系统进不去，我神舟机型跟你的一样的

**Comment by 1zilc** [comment]
好的,感谢反馈, 我一会把修改后的EFI 推上来

**Comment by DANGXingJie** [comment]
我重新下载了替换了，还是一样的问题，10.15.2系统进不去，明明跟您的机型一样的k610D I5 D3
太奇怪了！

**Comment by 1zilc** [comment]
试试新版的吧
