### ISSUE TITLE
最新的clover无法安装10.15.4

### ISSUE THREAD

**Issue by jhsking** [1zilc/K610d-i5-d3-10.14.5-efi-clover#27]
我用的3月4号的clover，无法安装10.15.4，总是卡进度条，因为卡死，无法抓取log，clover 啰嗦模式卡在了airport部分

**Comment by 1zilc** [comment]
你是从10.14.6升到10.15.4吗

**Comment by jhsking** [comment]
是的，以前用过10.15.2，但不稳定，后来退回去了，这次更新出问题了，还更新吗？邮件已经发了啰嗦模式的截图

**Comment by 1zilc** [comment]
每次更新之前记得升级clover

**Comment by jhsking** [comment]
更新了，依然不行，都到了5109了，难道要更新kext吗？

**Comment by 1zilc** [comment]
你上次发我的图我没有收到呢,这次是卡在哪里?

**Comment by 1zilc** [comment]
我已经上最新的5115了,也不行吗

**Comment by jhsking** [comment]
不行，跟原来的一个样，用黑果小兵的可以进去，你可以看看

**Comment by jhsking** [comment]
![QQ图片20200526182644](https://user-images.githubusercontent.com/56294375/82890314-8c7e3b00-9f7e-11ea-8c87-011bb1a32c8f.jpg)
我替换了1560无线网卡，就出现了这个问题，网上说10.15跟博通的无线网卡有冲突，不过黑果小兵的clover可以用，难道我装最新的10.15的时候要拆无线网卡？
