### ISSUE TITLE
使用15.4睡眠唤醒会重启

### ISSUE THREAD

**Issue by BABAICAI** [1zilc/K610d-i5-d3-10.14.5-efi-clover#29]
使用15.4的系统，自动睡眠唤醒之后，输入密码登陆，登陆一半时就会自己重启，重新进入到引导界面

**Comment by 1zilc** [comment]
你有没有尝试过删除appleALC?

**Comment by 1zilc** [comment]
经过排查,是hdmi audio的锅,最新版我已经修复了,感谢你的反馈
