### ISSUE TITLE
大神你好，关于无线wifi

### ISSUE THREAD

**Issue by rhymelph** [1zilc/K610d-i5-d3-10.14.5-efi-clover#3]
您好，先说一下我的情况吧，之前我在淘宝上面装了个10.13版本的黑苹果，然后发现不能升级系统，这个时候正好需要最新版本的xcode，所以自己尝试安装黑苹果，并且来到了这里，也发现了EFI这个东西，然后用之前淘宝装剩的EFI配置，在10.14.6版本下面只能用无线网卡wifi，其他的驱动像声卡驱动都不可以，了，然后用了大神你的EFI配置，所有驱动都可以（感谢），但唯独无线网卡wifi不行，所以请求大佬看看能不能两个EFI相结合，解决无线网卡的问题（貌似无线网卡的型号是AR9485,电脑也是战神k610i5d2）
下面是淘宝的EIF连接（clover版本比较老需要替换最新的版本）
https://github.com/rhymelph/10.13mac-EFI

**Comment by cyixlq** [comment]
2019.7.21
更新clover至5018,理论上支持macOS Catalina 10.15 beta4
更新lilu.kext至1.3.7
更新AppleALC.kext至1.3.9
更新WhateverGreen.kext至1.3.0 (三件套增加对10.15的支持,详细更新内容自行查看:https://github.com/acidanthera)
关于AR 9485的驱动,感谢i0Ek3的issure,将Atheros9485目录下的驱动放至S/L/E,再使用kext utility重建缓存即可
添加了ATH9KFixup.kext,且添加启动参数-ath9485


不行的话还是直接换无线网卡吧

**Comment by rhymelph** [comment]
写到S/L/E不行哦，好像不支持Atheros9485这个驱动了，淘宝里面的EFI里也没有这个驱动，也可以使用无线wifi，目前使用网线了,哈哈

**Comment by cyixlq** [comment]
建议还是换一块网卡

**Comment by rhymelph** [comment]
大佬用的是哪个网卡，我看看能不能换，驱动的好使不？

**Comment by cyixlq** [comment]
我用的是免驱的，但是我觉速度很慢，我用Windows原厂无线网卡速度1M多，黑苹果买的淘宝卡速度300K左右。所以我直接用最新win10了，已经买了白果。所以我用的就不推荐了，当时买的是3,40块钱

**Comment by cyixlq** [comment]
你可以去远景看看大家推荐哪款

**Comment by rhymelph** [comment]
好的大佬，感谢！

**Comment by cyixlq** [comment]
另外说一句，我不是这个库的作者，不要看错了哦。刚刚说的只是我个人建议

**Comment by rhymelph** [comment]
**看错了，哈哈哈**

**Comment by 1zilc** [comment]
暂时未在你提供的EFI中发现AR9485的驱动踪迹,驱动原理我还不是很明确

**Comment by 1zilc** [comment]
这个issue可以暂时不用关哈,关于AR9485,几种驱动方式我都试过,甚至连wifi图标都没出现,我也希望有人能提供明确的驱动方式,mojave下以前的驱动方式貌似都失效了
感兴趣的可以参考:
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1781566
http://bbs.pcbeta.com/viewthread-1823052-1-1.html
http://bbs.pcbeta.com/viewthread-1806854-1-1.html

**Comment by whhjdi** [comment]
AR9485驱动问题可以参考这个帖子
http://bbs.pcbeta.com/viewthread-1790406-1-1.html
https://github.com/athlonreg/ATH9KFixup

**Comment by 1zilc** [comment]
参考[AR9485 issue](https://github.com/1zilc/K610d-i5-d3-10.14.5-efi-clover/issues/15)
