### ISSUE TITLE
问一下，有没有comfast wu810n驱动？

### ISSUE THREAD

**Issue by kanhai-ps** [1zilc/K610d-i5-d3-10.14.5-efi-clover#38]
如题

**Comment by 1zilc** [comment]
可以试试这个 http://www.comfast.com.cn/index.php?m=content&c=index&a=show&catid=30&id=220

**Comment by as614001** [comment]
要不改天我推个OC pr 你合并？

**Comment by 1zilc** [comment]
> 要不改天我推个OC pr 你合并？

我这边没法测试哟～

**Comment by 1zilc** [comment]
> 要不改天我推个OC pr 你合并？

可以哈
