### ISSUE TITLE
请问你的内部麦克风能输入声音吗

### ISSUE THREAD

**Issue by phenixcxz** [1zilc/K610d-i5-d3-10.14.5-efi-clover#4]
试了好多的id,就是不能输入声音

**Comment by 1zilc** [comment]
麦克风没有问题,我的Siri都是可以直接使用的

**Comment by phenixcxz** [comment]
感谢你的回复，我的笔记本是K610c和你的配置有点不一样，使用你的配置检测不到音频端口，请问你的声卡是VT1802吗，你的config里面没有注入audio的端口,ssdt里面的alc里也没有发现注入端口，请问你是在什么地方设置的声卡，我想照着修改一下，非常感谢
