### ISSUE TITLE
关于外接HDMI 显示器的问题

### ISSUE THREAD

**Issue by whhjdi** [1zilc/K610d-i5-d3-10.14.5-efi-clover#5]
使用hanckintool生成的补丁外界显示器是有问题的，
可以替换我找到的这个
`<key>Properties</key>
		<dict>
			<key>PciRoot(0)/Pci(0x02,0)</key>
			<dict>
				<key>## patch0</key>
				<string>开机鼠标卡顿</string>
				<key>## patch1</key>
				<string>Enable internal display after sleep for 0x0a2e000a, 0x0a26000a</string>
				<key>##### 开启128M DVMT-prealloc，外接4k显示器需要，但是内置屏幕会狂闪</key>
				<string>0</string>
				<key>#####framebuffer-fbmem</key>
				<data>
				AAAAAg==
				</data>
				<key>#####framebuffer-stolenmem</key>
				<data>
				AAAACA==
				</data>
				<key>####framebuffer-fbmem</key>
				<data>
				AAAAAw==
				</data>
				<key>####framebuffer-stolenmem</key>
				<data>
				AAAABg==
				</data>
				<key>###framebuffer-fbmem</key>
				<data>
				AACQAA==
				</data>
				<key>###framebuffer-stolenmem</key>
				<data>
				AABgAA==
				</data>
				<key>#hda-gfx</key>
				<string>onboard-1</string>
				<key>AAPL,ig-platform-id</key>
				<data>
				BgAmCg==
				</data>
				<key>AAPL00,override-no-edid</key>
				<data>
				AP///////wAGrz0UAAAAAAAXAQSVHxF4Arv1lFVUkCcj
				UFQAAAABAQEBAQEBAQEBAQEBAQEBsDaASnE4NEAwIDUA
				Na0QAAAYAAAADwAAAAAAAAAAAAAAAAAgAAAA/gBBVU8K
				ICAgICAgICAgAAAA/gBCMTQwSFROMDEuNCAKAOY=
				</data>
				<key>device-id</key>
				<data>
				EgQAAA==
				</data>
				<key>enable-hdmi20</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-enable</key>
				<integer>1</integer>
				<key>framebuffer-con1-flags</key>
				<data>
				BgAAAA==
				</data>
				<key>framebuffer-con1-pipe</key>
				<data>
				EgAAAA==
				</data>
				<key>framebuffer-con1-type</key>
				<data>
				AAgAAA==
				</data>
				<key>framebuffer-cursormem</key>
				<data>
				AACQAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<integer>1</integer>
				<key>framebuffer-patch0-enable</key>
				<integer>1</integer>
				<key>framebuffer-patch0-find</key>
				<data>
				AgQJAAAEAACHAAAA
				</data>
				<key>framebuffer-patch0-replace</key>
				<data>
				/wAJAAAEAACHAAAA
				</data>
				<key>framebuffer-patch1-enable</key>
				<integer>1</integer>
				<key>framebuffer-patch1-find</key>
				<data>
				AQAAAEAAAAAeAgAABQUJAQ==
				</data>
				<key>framebuffer-patch1-replace</key>
				<data>
				AQAAAEAAAAAfAgAABQUJAQ==
				</data>
				<key>framebuffer-patch2-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-patch2-find</key>
				<data>
				AwAiDQADAwMAAAACAAAwAQAAAAAAAABgmRQ=
				</data>
				<key>framebuffer-patch2-replace</key>
				<data>
				AwAiDQADAwMAAAAIAAAAAgAAAAAAAACAmRQ=
				</data>
				<key>framebuffer-unifiedmem</key>
				<data>
				AAAAgA==
				</data>
				<key>model</key>
				<string>Intel HD Graphics 4600</string>
			</dict>
		</dict>`

**Comment by 1zilc** [comment]
外接hdmi有什么问题,具体表现是什么

**Comment by whhjdi** [comment]
外接显示器的尺寸识别错误，我的是24寸2k,识别成27的1080
之前我用ym2008的efi也有这种问题，我换了缓冲帧修补的代码才解决

**Comment by whhjdi** [comment]
下边这两个dvmt相关的可以不打，就没问题了
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>

**Comment by 1zilc** [comment]
关于这两项,你可以根据自己的情况来设置,去掉应该是太不可能的
**建议:**

- framebuffer-fbmem
一般屏幕设置成9M：00009000 -> AACQAA==
高分屏设置成48M：00000003 -> AAAAAw==

- framebuffer-stolenmem
1080P，设置为48M：00003001 -> AAAwAQ==
2k，设置为64M：00000004 -> AAAABA==
4K，要设置为128M：00000008 -> AAAACA==

**Comment by whhjdi** [comment]
> 关于这两项,你可以根据自己的情况来设置,去掉应该是太不可能的
> **建议:**
> 
> * framebuffer-fbmem
>   一般屏幕设置成9M：00009000 -> AACQAA==
>   高分屏设置成48M：00000003 -> AAAAAw==
> * framebuffer-stolenmem
>   1080P，设置为48M：00003001 -> AAAwAQ==
>   2k，设置为64M：00000004 -> AAAABA==
>   4K，要设置为128M：00000008 -> AAAACA==

这是whatevergreen提供的hd4600的一个配置，只需要在增加framebuffer-unifiedmem，把显存提高到2048M就行，不弄也行
这两项真的可以去掉的，修补这两项其实没啥用（可能bios的问题）
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/AzulPatcher4600_equivalent.plist

**Comment by ZeYuYang1024** [comment]
我更新了最新版的efi之后 外接显示器就黑屏

**Comment by 1zilc** [comment]
> 我更新了最新版的efi之后 外接显示器就黑屏

不排除是virtualSmc的问题, 先用fakeSMC的release吧https://github.com/1zilc/K610d-i5-d3-10.14.5-efi-clover/releases/tag/10.15.2
