### ISSUE TITLE
你好，请问我替换了你的EFI怎么驱动不生效

### ISSUE THREAD

**Issue by DANGXingJie** [1zilc/K610d-i5-d3-10.14.5-efi-clover#6]

**Comment by 1zilc** [comment]
请你说详细一点

**Comment by DANGXingJie** [comment]
感谢你能回复，我知道问题了，是装Mac的ESP分区没放在电脑第一启动，现在可以了，只不过有花屏，是屏幕的EDID没有注入，但是 为什么声卡也不生效，没有声音，电池的图标也出不来

**Comment by DANGXingJie** [comment]
我屏幕的EDID也用工具注入了，但是开机还是花屏，设置休眠后再点亮就显示正常点，但是会一直闪屏，该打什么补丁好
