### ISSUE TITLE
10.15出了，还会更新吗？

### ISSUE THREAD

**Issue by zhuweijia** [1zilc/K610d-i5-d3-10.14.5-efi-clover#8]
我的是神舟K550d i5的处理器，感觉跟你的配置差不多，好像就是显卡不一样，不知道能不能直接用你的EFI啊？
10.15 出了，还会继续更新吗？

**Comment by 1zilc** [comment]
会跟进支持10.15的^_^

**Comment by jhsking** [comment]
我用你最新的clover，安装后可以正常运行，但第二天就会在白苹果标那无限重启，替换了远景论坛的config.list可以起来，但风扇狂转。啰嗦模式也是走代码走到一半然后重启，你还是更新一下吧。在10.14.6很正常

**Comment by 1zilc** [comment]
提供一下你的系统版本号,以及debug.log谢谢 🙏

**Comment by jhsking** [comment]
版本号10.15.1，因为退回10.14.6了，无法提取debug.log

**Comment by 1zilc** [comment]
暂时更新了一下,你可以先试试看 , 我现在有个VirtualSMC版的还没有上传, 最近比较忙,没空搞

**Comment by jhsking** [comment]
> 暂时更新了一下,你可以先试试看 , 我现在有个VirtualSMC版的还没有上传, 最近比较忙,没空搞

更新了你最新的，依旧重启，不可用依然 10.15.1
[preboot.log](https://github.com/1zilc/K610d-i5-d3-10.14.5-efi-clover/files/3878304/preboot.log)

**Comment by jhsking** [comment]
重新提取了一次
[preboot.log](https://github.com/1zilc/K610d-i5-d3-10.14.5-efi-clover/files/3878369/preboot.log)

**Comment by jhsking** [comment]
我找了一个VirtualSMC，替换了照样没用，依然重启

**Comment by 1zilc** [comment]
方便的话发一下啰嗦模式的照片

**Comment by 1zilc** [comment]
大概率是卡applePS2,我很早就加了EC的改名补丁

**Comment by jhsking** [comment]
另外安装了10.14.6最新的一个补丁，也是开始开机无限重启
